### ISSUE TITLE
Enhancement: Add option for outside labels

### ISSUE THREAD

**Issue by guyzk** [apgapg/pie_chart#8]
As of now if there are a lot of segments in the chart the label values (in the pie) are cut by one another.
It would be great if there was an option to have outside labels something like:
https://google.github.io/charts/flutter/example/pie_charts/outside_label

**Comment by apgapg** [comment]
Hi i understand your point. But what i think is even when values are outside of chart as in the pic you mentioned, again the cluttering could happen if segments are small. The strategy used by the chart lib is the use of arrows which requires a little complex code. For now i just give a param to show them outside instead of inside the chart

**Comment by apgapg** [comment]
Done check v1.0.0

**Comment by guyzk** [comment]
Thanks for the quick response.
I believe your quick fix is OK for now (thanks by the way!) But I definitely think that arrows will be a very good addition. Hope you could get to that in future versions.
Good job!
